# Generated by Django 5.0.2 on 2024-02-16 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('organization', models.TextField()),
                ('cn', models.TextField()),
                ('key', models.TextField()),
                ('cert', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('organization', models.TextField()),
                ('cn', models.TextField()),
                ('key', models.TextField()),
                ('cert', models.TextField()),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpn.ca')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('organization', models.TextField()),
                ('cn', models.TextField()),
                ('user_id', models.TextField()),
                ('key', models.TextField()),
                ('cert', models.TextField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpn.server')),
            ],
        ),
    ]
